services:
  # API Service
  api:
    build:
      context: .
      dockerfile: API/Dockerfile
    container_name: h2-api
    ports:
      - "8050:8080"
      - "8051:8081"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:8080;https://+:8081
    networks:
      - h2-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Blazor WASM App
  blazor:
    build:
      context: .
      dockerfile: Blazor/Dockerfile
    container_name: h2-blazor
    ports:
      - "8052:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - API_ENDPOINT_DOCKER=http://api:8080/
      - API_ENDPOINT_LOCAL=http://localhost:5253/
      - API_ENDPOINT_PRODUCTION=https://h2-api.mercantec.tech/
    depends_on:
      api:
        condition: service_healthy
    networks:
      - h2-network
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

networks:
  h2-network:
    driver: bridge
